Skip action if branch matches a regex

diff --git a/actions/save-dependabot-changes/action.yml b/actions/save-dependabot-changes/action.yml
--- a/actions/save-dependabot-changes/action.yml
+++ b/actions/save-dependabot-changes/action.yml
@@ -8,6 +8,10 @@ inputs:
       See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow for more info.
     required: true
 
+  branches_to_skip:
+    description: Regex of branches where this action should not run. e.g. 'master'
+    required: true
+
 outputs:
   is_dirty:
     description: "If there were changes made by dependabot, this variable will be true"
@@ -33,6 +37,17 @@ runs:
           echo "SKIP=true" >> $GITHUB_OUTPUT
           exit
         fi        
+
+        if [[ -z "${{ inputs.branches_to_skip }}" ]]; then
+          echo '::error:: Action save-dependabot-changes requires that parameter branches_to_skip have a non-empty value'
+          exit 1
+        fi
+
+        if grep --silent -E "${{ inputs.branches_to_skip }}" <(echo "${SOURCE_BRANCH}"); then
+          echo '::notice:: Action save-dependabot-changes is being skipped because branch matches the branches_to_skip regex'
+          echo "SKIP=true" >> $GITHUB_OUTPUT
+          exit
+        fi
 
     - name: Check if dependencies changed
       if: steps.preconditions.outputs.SKIP != 'true'
