Update action tests to check that the dependency files were updated.

diff --git a/.github/workflows/test-action.yml b/.github/workflows/test-action.yml
--- a/.github/workflows/test-action.yml
+++ b/.github/workflows/test-action.yml
@@ -55,6 +55,7 @@ jobs:
       - name: "Check that action didn't do any changes"
         run: |
           if [[ "${{ steps.changed-by-dependabot.outputs.is_dirty }}"  == 'true' ]]; then
+            echo "::error:: Action indicates that the repo was dirty" 
             exit 1
           fi
 
@@ -70,5 +71,18 @@ jobs:
         if: github.ref_type == 'branch'
         run: |
           if [[ "${{ steps.changed-by-dependabot2.outputs.is_dirty }}"  != 'true' ]]; then
+            echo "::error:: Action indicates that the repo was not dirty" 
+            exit 1
+          fi
+
+          DESTINATION_BRANCH="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
+          DIFF=$(git diff --stat --cached  origin/${DESTINATION_BRANCH})
+          if [[ -z "${DIFF}" ]]; then
+            echo "::error:: There weren't any files committed." 
+            exit 1
+          fi
+
+          if ! grep -e '^\s*DEPENDENCY_LICENSES.md' <(echo "${DIFF}") > /dev/null; then
+            echo "::error:: File DEPENDENCY_LICENSES.md was not modified, but it should have been." 
             exit 1
           fi
